sudo: false
matrix:
  allow_failures:
    - os: osx
    - python: 3.7-dev
    - python: pypy
    - python: pypy3.3-5.2-alpha1
  include:
    - language: python
      python: 3.4
    - language: python
      python: 3.5
    - language: python
      python: 3.6
    - language: python
      python: 3.7-dev
    - language: python
      python: pypy
    - language: python
      dist: trusty

    # no Python on OS X still, using node_js for now...
    - language: node_js
      node_js: 4.6
      os: osx
      env:
        - TRAVIS_PYTHON_VERSION=3.4.5
    - language: node_js
      node_js: 6.9
      os: osx
      env:
        - TRAVIS_PYTHON_VERSION=3.5.3
    - language: node_js
      node_js: 7.4
      os: osx
      env:
        - TRAVIS_PYTHON_VERSION=3.6.0

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update || brew update ;
      brew install pyenv ;
      brew outdated pyenv || brew upgrade pyenv ;
      pyenv install $TRAVIS_PYTHON_VERSION ;
      pyenv global $TRAVIS_PYTHON_VERSION ;
      eval "$(pyenv init -)" ;
      python --version ;
      python -m pip install --user virtualenv ;
      python -m virtualenv ~/.venv ;
      source ~/.venv/bin/activate ;
    else
      export DISPLAY=:99.0 ;
      sh -e /etc/init.d/xvfb start ;
      rm -rf ~/.nvm ;
      git clone https://github.com/creationix/nvm.git ~/.nvm ;
      (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags` );
      source ~/.nvm/nvm.sh ;
      nvm install "$TRAVIS_NODE_VERSION" ;
    fi
  - node --version
  - npm --version

install:
  - pip install coverage flake8
  - pip install sanic
  - python setup.py develop
script:
  - flake8 setup.py src
  - coverage run --include=src/* -m unittest repodono.jobs.tests.make_suite
  - coverage report -m

after_success:
  # only submit coverage when testing under linux.
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      pip install coveralls;
      coveralls
    fi

branches:
  only:
    - testing
    - master
    - 1.0.x
